pcall(function()
    print(" ")
    print("==========================================")
    print("UPF Protection Framework UI loaded")
    print("Author: Sourcerer")
    print("Co-Developer: markuriel2010")
    print("Repository: script_roblox_proteccion_experimental")
    print("==========================================")
    print(" ")
end)

print("✅ Credits loader")
