pcall(function()
    print(" ")
    print("==========================================")
    print("UPF Framework loaded")
    print("Author: markuriel2010")
    print("Co-Developer: markuriel mc")
    print("Teclas/Keyboard")
    print("K  UI")
    print("M  Cambiar Modo")
    print("P  Aplicar Efecto")
    print("Fechas: Derecha/Izquierda  Cambiar Asset")
    print("==========================================")
    print(" ")
end)
